package org.example;

import java.util.Scanner;

/**
 * Print diamond generated by Diamond.print(char)
 */
public class App {
    public static void main(String[] args) {

        Scanner scanner = new Scanner(System.in);

        while (true) {
            System.out.println("Enter a character a-z/A-Z (type ':q' to quit): \n");
            String input = scanner.nextLine();
            if (input.equalsIgnoreCase(":q")) {
                break;
            }
            if (input.matches("([a-z])|([A-Z])")) {
                char c = input.charAt(0);
                System.out.println("\n Generating diamond... \n");
                System.out.println(Diamond.create(c) + "\n");
            }
        }

        System.out.println("\n Exiting...");
        scanner.close();
    }
}
